/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Combined API for TikTok-style app and FindBuilders platform
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface SuccessResponse {
  success: boolean;
}

export interface Video {
  id: number;
  userId: number;
  username: string;
  displayName: string;
  avatarUrl?: string | null;
  title: string;
  description?: string | null;
  videoUrl: string;
  thumbnailUrl?: string | null;
  tags: string[];
  likesCount: number;
  commentsCount: number;
  viewsCount: number;
  isLiked: boolean;
  createdAt: string;
}

export interface VideoListResponse {
  videos: Video[];
  total: number;
  page: number;
  totalPages: number;
}

export interface CreateVideoBody {
  title: string;
  description?: string | null;
  videoUrl: string;
  thumbnailUrl?: string | null;
  tags?: string[];
  userId: number;
}

export interface LikeVideoBody {
  userId: number;
  liked: boolean;
}

export interface LikeResponse {
  liked: boolean;
  likesCount: number;
}

export interface Comment {
  id: number;
  videoId: number;
  userId: number;
  username: string;
  displayName: string;
  avatarUrl?: string | null;
  text: string;
  createdAt: string;
}

export interface CommentListResponse {
  comments: Comment[];
  total: number;
}

export interface CreateCommentBody {
  userId: number;
  text: string;
}

export interface User {
  id: number;
  username: string;
  displayName: string;
  avatarUrl?: string | null;
  bio?: string | null;
  followersCount: number;
  followingCount: number;
  videosCount: number;
  isFollowing: boolean;
}

export interface FollowUserBody {
  followerId: number;
  following: boolean;
}

export interface FollowResponse {
  following: boolean;
  followersCount: number;
}

export interface Lead {
  id: number;
  title: string;
  description: string;
  category: string;
  location: string;
  city: string;
  state: string;
  budgetMin: number;
  budgetMax: number;
  timeline: string;
  startDate?: string | null;
  isUrgent: boolean;
  isVerified: boolean;
  interestedCount: number;
  tags: string[];
  clientName: string;
  postedAt: string;
  expiresAt?: string | null;
}

export interface LeadListResponse {
  leads: Lead[];
  total: number;
  page: number;
  totalPages: number;
}

export interface CreateLeadRequest {
  title: string;
  description: string;
  category: string;
  city: string;
  state: string;
  budgetMin: number;
  budgetMax: number;
  timeline: string;
  startDate?: string | null;
  isUrgent?: boolean;
  tags?: string[];
  clientName: string;
  clientEmail: string;
  clientPhone?: string | null;
}

export interface LeadContact {
  leadId: number;
  clientName: string;
  clientEmail: string;
  clientPhone?: string | null;
  address?: string | null;
}

export interface Category {
  id: number;
  name: string;
  slug: string;
  icon: string;
  leadsCount: number;
}

export interface CategoryListResponse {
  categories: Category[];
}

export interface PlatformStats {
  totalLeads: number;
  totalContractors: number;
  totalProjectsCompleted: number;
  averageResponseTime: string;
}

export type ListVideosParams = {
  page?: number;
  limit?: number;
  userId?: number;
};

export type ListCommentsParams = {
  page?: number;
  limit?: number;
};

export type ListLeadsParams = {
  page?: number;
  limit?: number;
  category?: string;
  location?: string;
  minBudget?: number;
  maxBudget?: number;
  search?: string;
};
