/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Combined API for TikTok-style app and FindBuilders platform
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CategoryListResponse,
  Comment,
  CommentListResponse,
  CreateCommentBody,
  CreateLeadRequest,
  CreateVideoBody,
  FollowResponse,
  FollowUserBody,
  HealthStatus,
  Lead,
  LeadContact,
  LeadListResponse,
  LikeResponse,
  LikeVideoBody,
  ListCommentsParams,
  ListLeadsParams,
  ListVideosParams,
  PlatformStats,
  SuccessResponse,
  User,
  Video,
  VideoListResponse,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List videos
 */
export const getListVideosUrl = (params?: ListVideosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/videos?${stringifiedParams}`
    : `/api/videos`;
};

export const listVideos = async (
  params?: ListVideosParams,
  options?: RequestInit,
): Promise<VideoListResponse> => {
  return customFetch<VideoListResponse>(getListVideosUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListVideosQueryKey = (params?: ListVideosParams) => {
  return [`/api/videos`, ...(params ? [params] : [])] as const;
};

export const getListVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ErrorType<unknown>,
>(
  params?: ListVideosParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listVideos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListVideosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listVideos>>> = ({
    signal,
  }) => listVideos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listVideos>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVideos>>
>;
export type ListVideosQueryError = ErrorType<unknown>;

/**
 * @summary List videos
 */

export function useListVideos<
  TData = Awaited<ReturnType<typeof listVideos>>,
  TError = ErrorType<unknown>,
>(
  params?: ListVideosParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listVideos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListVideosQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a video
 */
export const getCreateVideoUrl = () => {
  return `/api/videos`;
};

export const createVideo = async (
  createVideoBody: CreateVideoBody,
  options?: RequestInit,
): Promise<Video> => {
  return customFetch<Video>(getCreateVideoUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createVideoBody),
  });
};

export const getCreateVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVideo>>,
    TError,
    { data: BodyType<CreateVideoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createVideo>>,
  TError,
  { data: BodyType<CreateVideoBody> },
  TContext
> => {
  const mutationKey = ["createVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createVideo>>,
    { data: BodyType<CreateVideoBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createVideo(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof createVideo>>
>;
export type CreateVideoMutationBody = BodyType<CreateVideoBody>;
export type CreateVideoMutationError = ErrorType<unknown>;

/**
 * @summary Create a video
 */
export const useCreateVideo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVideo>>,
    TError,
    { data: BodyType<CreateVideoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createVideo>>,
  TError,
  { data: BodyType<CreateVideoBody> },
  TContext
> => {
  return useMutation(getCreateVideoMutationOptions(options));
};

/**
 * @summary Get a single video
 */
export const getGetVideoUrl = (id: number) => {
  return `/api/videos/${id}`;
};

export const getVideo = async (
  id: number,
  options?: RequestInit,
): Promise<Video> => {
  return customFetch<Video>(getGetVideoUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetVideoQueryKey = (id: number) => {
  return [`/api/videos/${id}`] as const;
};

export const getGetVideoQueryOptions = <
  TData = Awaited<ReturnType<typeof getVideo>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getVideo>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVideoQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideo>>> = ({
    signal,
  }) => getVideo(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getVideo>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetVideoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getVideo>>
>;
export type GetVideoQueryError = ErrorType<void>;

/**
 * @summary Get a single video
 */

export function useGetVideo<
  TData = Awaited<ReturnType<typeof getVideo>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getVideo>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetVideoQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a video
 */
export const getDeleteVideoUrl = (id: number) => {
  return `/api/videos/${id}`;
};

export const deleteVideo = async (
  id: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteVideoUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVideo>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVideo>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVideo>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteVideo(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteVideo>>
>;

export type DeleteVideoMutationError = ErrorType<unknown>;

/**
 * @summary Delete a video
 */
export const useDeleteVideo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVideo>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteVideo>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteVideoMutationOptions(options));
};

/**
 * @summary Like or unlike a video
 */
export const getLikeVideoUrl = (id: number) => {
  return `/api/videos/${id}/like`;
};

export const likeVideo = async (
  id: number,
  likeVideoBody: LikeVideoBody,
  options?: RequestInit,
): Promise<LikeResponse> => {
  return customFetch<LikeResponse>(getLikeVideoUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(likeVideoBody),
  });
};

export const getLikeVideoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeVideo>>,
    TError,
    { id: number; data: BodyType<LikeVideoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof likeVideo>>,
  TError,
  { id: number; data: BodyType<LikeVideoBody> },
  TContext
> => {
  const mutationKey = ["likeVideo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof likeVideo>>,
    { id: number; data: BodyType<LikeVideoBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return likeVideo(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LikeVideoMutationResult = NonNullable<
  Awaited<ReturnType<typeof likeVideo>>
>;
export type LikeVideoMutationBody = BodyType<LikeVideoBody>;
export type LikeVideoMutationError = ErrorType<unknown>;

/**
 * @summary Like or unlike a video
 */
export const useLikeVideo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeVideo>>,
    TError,
    { id: number; data: BodyType<LikeVideoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof likeVideo>>,
  TError,
  { id: number; data: BodyType<LikeVideoBody> },
  TContext
> => {
  return useMutation(getLikeVideoMutationOptions(options));
};

/**
 * @summary List comments on a video
 */
export const getListCommentsUrl = (id: number, params?: ListCommentsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/videos/${id}/comments?${stringifiedParams}`
    : `/api/videos/${id}/comments`;
};

export const listComments = async (
  id: number,
  params?: ListCommentsParams,
  options?: RequestInit,
): Promise<CommentListResponse> => {
  return customFetch<CommentListResponse>(getListCommentsUrl(id, params), {
    ...options,
    method: "GET",
  });
};

export const getListCommentsQueryKey = (
  id: number,
  params?: ListCommentsParams,
) => {
  return [`/api/videos/${id}/comments`, ...(params ? [params] : [])] as const;
};

export const getListCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  params?: ListCommentsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listComments>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListCommentsQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listComments>>> = ({
    signal,
  }) => listComments(id, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listComments>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listComments>>
>;
export type ListCommentsQueryError = ErrorType<unknown>;

/**
 * @summary List comments on a video
 */

export function useListComments<
  TData = Awaited<ReturnType<typeof listComments>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  params?: ListCommentsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listComments>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCommentsQueryOptions(id, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Post a comment on a video
 */
export const getCreateCommentUrl = (id: number) => {
  return `/api/videos/${id}/comments`;
};

export const createComment = async (
  id: number,
  createCommentBody: CreateCommentBody,
  options?: RequestInit,
): Promise<Comment> => {
  return customFetch<Comment>(getCreateCommentUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCommentBody),
  });
};

export const getCreateCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createComment>>,
    TError,
    { id: number; data: BodyType<CreateCommentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  { id: number; data: BodyType<CreateCommentBody> },
  TContext
> => {
  const mutationKey = ["createComment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createComment>>,
    { id: number; data: BodyType<CreateCommentBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return createComment(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createComment>>
>;
export type CreateCommentMutationBody = BodyType<CreateCommentBody>;
export type CreateCommentMutationError = ErrorType<unknown>;

/**
 * @summary Post a comment on a video
 */
export const useCreateComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createComment>>,
    TError,
    { id: number; data: BodyType<CreateCommentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  { id: number; data: BodyType<CreateCommentBody> },
  TContext
> => {
  return useMutation(getCreateCommentMutationOptions(options));
};

/**
 * @summary Get user profile
 */
export const getGetUserUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const getUser = async (
  id: number,
  options?: RequestInit,
): Promise<User> => {
  return customFetch<User>(getGetUserUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetUserQueryKey = (id: number) => {
  return [`/api/users/${id}`] as const;
};

export const getGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({
    signal,
  }) => getUser(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUser>>
>;
export type GetUserQueryError = ErrorType<void>;

/**
 * @summary Get user profile
 */

export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Follow or unfollow a user
 */
export const getFollowUserUrl = (id: number) => {
  return `/api/users/${id}/follow`;
};

export const followUser = async (
  id: number,
  followUserBody: FollowUserBody,
  options?: RequestInit,
): Promise<FollowResponse> => {
  return customFetch<FollowResponse>(getFollowUserUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(followUserBody),
  });
};

export const getFollowUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof followUser>>,
    TError,
    { id: number; data: BodyType<FollowUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof followUser>>,
  TError,
  { id: number; data: BodyType<FollowUserBody> },
  TContext
> => {
  const mutationKey = ["followUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof followUser>>,
    { id: number; data: BodyType<FollowUserBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return followUser(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FollowUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof followUser>>
>;
export type FollowUserMutationBody = BodyType<FollowUserBody>;
export type FollowUserMutationError = ErrorType<unknown>;

/**
 * @summary Follow or unfollow a user
 */
export const useFollowUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof followUser>>,
    TError,
    { id: number; data: BodyType<FollowUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof followUser>>,
  TError,
  { id: number; data: BodyType<FollowUserBody> },
  TContext
> => {
  return useMutation(getFollowUserMutationOptions(options));
};

/**
 * @summary List construction leads
 */
export const getListLeadsUrl = (params?: ListLeadsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/leads?${stringifiedParams}`
    : `/api/leads`;
};

export const listLeads = async (
  params?: ListLeadsParams,
  options?: RequestInit,
): Promise<LeadListResponse> => {
  return customFetch<LeadListResponse>(getListLeadsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListLeadsQueryKey = (params?: ListLeadsParams) => {
  return [`/api/leads`, ...(params ? [params] : [])] as const;
};

export const getListLeadsQueryOptions = <
  TData = Awaited<ReturnType<typeof listLeads>>,
  TError = ErrorType<unknown>,
>(
  params?: ListLeadsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listLeads>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListLeadsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listLeads>>> = ({
    signal,
  }) => listLeads(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listLeads>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListLeadsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listLeads>>
>;
export type ListLeadsQueryError = ErrorType<unknown>;

/**
 * @summary List construction leads
 */

export function useListLeads<
  TData = Awaited<ReturnType<typeof listLeads>>,
  TError = ErrorType<unknown>,
>(
  params?: ListLeadsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listLeads>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListLeadsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Post a new project lead
 */
export const getCreateLeadUrl = () => {
  return `/api/leads`;
};

export const createLead = async (
  createLeadRequest: CreateLeadRequest,
  options?: RequestInit,
): Promise<Lead> => {
  return customFetch<Lead>(getCreateLeadUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createLeadRequest),
  });
};

export const getCreateLeadMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLead>>,
    TError,
    { data: BodyType<CreateLeadRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLead>>,
  TError,
  { data: BodyType<CreateLeadRequest> },
  TContext
> => {
  const mutationKey = ["createLead"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLead>>,
    { data: BodyType<CreateLeadRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createLead(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLeadMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLead>>
>;
export type CreateLeadMutationBody = BodyType<CreateLeadRequest>;
export type CreateLeadMutationError = ErrorType<unknown>;

/**
 * @summary Post a new project lead
 */
export const useCreateLead = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLead>>,
    TError,
    { data: BodyType<CreateLeadRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createLead>>,
  TError,
  { data: BodyType<CreateLeadRequest> },
  TContext
> => {
  return useMutation(getCreateLeadMutationOptions(options));
};

/**
 * @summary Get a single lead
 */
export const getGetLeadUrl = (id: number) => {
  return `/api/leads/${id}`;
};

export const getLead = async (
  id: number,
  options?: RequestInit,
): Promise<Lead> => {
  return customFetch<Lead>(getGetLeadUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetLeadQueryKey = (id: number) => {
  return [`/api/leads/${id}`] as const;
};

export const getGetLeadQueryOptions = <
  TData = Awaited<ReturnType<typeof getLead>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getLead>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLeadQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLead>>> = ({
    signal,
  }) => getLead(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getLead>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetLeadQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLead>>
>;
export type GetLeadQueryError = ErrorType<void>;

/**
 * @summary Get a single lead
 */

export function useGetLead<
  TData = Awaited<ReturnType<typeof getLead>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getLead>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLeadQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Unlock contact for a lead
 */
export const getContactLeadUrl = (id: number) => {
  return `/api/leads/${id}/contact`;
};

export const contactLead = async (
  id: number,
  options?: RequestInit,
): Promise<LeadContact> => {
  return customFetch<LeadContact>(getContactLeadUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getContactLeadMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contactLead>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contactLead>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["contactLead"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contactLead>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return contactLead(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContactLeadMutationResult = NonNullable<
  Awaited<ReturnType<typeof contactLead>>
>;

export type ContactLeadMutationError = ErrorType<unknown>;

/**
 * @summary Unlock contact for a lead
 */
export const useContactLead = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contactLead>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof contactLead>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getContactLeadMutationOptions(options));
};

/**
 * @summary List all trade categories
 */
export const getListCategoriesUrl = () => {
  return `/api/categories`;
};

export const listCategories = async (
  options?: RequestInit,
): Promise<CategoryListResponse> => {
  return customFetch<CategoryListResponse>(getListCategoriesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListCategoriesQueryKey = () => {
  return [`/api/categories`] as const;
};

export const getListCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof listCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCategories>>> = ({
    signal,
  }) => listCategories({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCategories>>
>;
export type ListCategoriesQueryError = ErrorType<unknown>;

/**
 * @summary List all trade categories
 */

export function useListCategories<
  TData = Awaited<ReturnType<typeof listCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCategoriesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Platform statistics
 */
export const getGetStatsUrl = () => {
  return `/api/stats`;
};

export const getStats = async (
  options?: RequestInit,
): Promise<PlatformStats> => {
  return customFetch<PlatformStats>(getGetStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetStatsQueryKey = () => {
  return [`/api/stats`] as const;
};

export const getGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({
    signal,
  }) => getStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStats>>
>;
export type GetStatsQueryError = ErrorType<unknown>;

/**
 * @summary Platform statistics
 */

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
